apiVersion: v1
kind: Pod
metadata:
  name: k8s-hello-world
  labels:
    name: k8s-hello-world
spec:
  containers:
    - name: k8s-hello-world
      image: icrosby/tinyping:v1
      ports:
        - containerPort: 8080
